use sopds;
drop table if exists genres;
drop table if exists bgenres;
commit;

create table genres(
genre_id INT not null AUTO_INCREMENT,
genre VARCHAR(32),
section VARCHAR(32),
subsection VARCHAR(32),
PRIMARY KEY(genre_id),
KEY(genre));
commit;

create table bgenres(
genre_id INT not NULL,
book_id INT not NULL,
PRIMARY KEY(book_id,genre_id));
commit;

insert into genres(genre,subsection,section) values("sf_history","Альтернативная история","Фантастика");
insert into genres(genre,subsection,section) values("sf_action","Боевая фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_epic","Эпическая фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_heroic","Героическая фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_detective","Детективная фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_cyberpunk","Киберпанк","Фантастика");
insert into genres(genre,subsection,section) values("sf_space","Космическая фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_social","Социально психологическая фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_horror","Ужасы и Мистика","Фантастика");
insert into genres(genre,subsection,section) values("sf_humor","Юмористическая фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_fantasy","Фэнтези","Фантастика");
insert into genres(genre,subsection,section) values("sf","Научная Фантастика","Фантастика");
insert into genres(genre,subsection,section) values("det_classic","Классический детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_police","Полицейский детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_action","Боевик","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_irony","Иронический детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_history","Исторический детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_espionage","Шпионский детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_crime","Криминальный детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_political","Политический детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_maniac","Маньяки","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_hard","Крутой детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("thriller","Триллер","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("detective","Детектив (не относящийся в прочие категории).","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("prose_classic","Классическая проза","Проза");
insert into genres(genre,subsection,section) values("prose_history","Историческая проза","Проза");
insert into genres(genre,subsection,section) values("prose_contemporary","Современная проза","Проза");
insert into genres(genre,subsection,section) values("prose_counter","Контркультура","Проза");
insert into genres(genre,subsection,section) values("prose_rus_classic","Русская классическая проза","Проза");
insert into genres(genre,subsection,section) values("prose_su_classics","Советская классическая проза","Проза");
insert into genres(genre,subsection,section) values("love_contemporary","Современные любовные романы","Любовные романы");
insert into genres(genre,subsection,section) values("love_history","Исторические любовные романы","Любовные романы");
insert into genres(genre,subsection,section) values("love_detective","Остросюжетные любовные романы","Любовные романы");
insert into genres(genre,subsection,section) values("love_short","Короткие любовные романы","Любовные романы");
insert into genres(genre,subsection,section) values("love_erotica","Эротика","Любовные романы");
insert into genres(genre,subsection,section) values("adv_western","Вестерн","Приключения");
insert into genres(genre,subsection,section) values("adv_history","Исторические приключения","Приключения");
insert into genres(genre,subsection,section) values("adv_indian","Приключения про индейцев","Приключения");
insert into genres(genre,subsection,section) values("adv_maritime","Морские приключения","Приключения");
insert into genres(genre,subsection,section) values("adv_geo","Путешествия и география","Приключения");
insert into genres(genre,subsection,section) values("adv_animal","Природа и животные","Приключения");
insert into genres(genre,subsection,section) values("adventure","Прочие приключения","Приключения");
insert into genres(genre,subsection,section) values("child_tale","Сказка","Детская литература");
insert into genres(genre,subsection,section) values("child_verse","Детские стихи","Детская литература");
insert into genres(genre,subsection,section) values("child_prose","Детскиая проза","Детская литература");
insert into genres(genre,subsection,section) values("child_sf","Детская фантастика","Детская литература");
insert into genres(genre,subsection,section) values("child_det","Детские остросюжетные","Детская литература");
insert into genres(genre,subsection,section) values("child_adv","Детские приключения","Детская литература");
insert into genres(genre,subsection,section) values("child_education","Детская образовательная литература","Детская литература");
insert into genres(genre,subsection,section) values("children","Прочая детская литература","Детская литература");
insert into genres(genre,subsection,section) values("poetry","Поэзия","Поэзия, Драматургия");
insert into genres(genre,subsection,section) values("dramaturgy","Драматургия","Поэзия, Драматургия");
insert into genres(genre,subsection,section) values("antique_ant","Античная литература","Старинное");
insert into genres(genre,subsection,section) values("antique_european","Европейская старинная литература","Старинное");
insert into genres(genre,subsection,section) values("antique_russian","Древнерусская литература","Старинное");
insert into genres(genre,subsection,section) values("antique_east","Древневосточная литература","Старинное");
insert into genres(genre,subsection,section) values("antique_myths","Мифы. Легенды. Эпос","Старинное");
insert into genres(genre,subsection,section) values("antique","Прочая старинная литература","Старинное");
insert into genres(genre,subsection,section) values("sci_history","История","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_psychology","Психология","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_culture","Культурология","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_religion","Религиоведение","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_philosophy","Философия","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_politics","Политика","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_business","Деловая литература","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_juris","Юриспруденция","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_linguistic","Языкознание","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_medicine","Медицина","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_phys","Физика","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_math","Математика","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_chem","Химия","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_biology","Биология","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_tech","Технические науки","Наука, Образование");
insert into genres(genre,subsection,section) values("science","Прочая научная литература","Наука, Образование");
insert into genres(genre,subsection,section) values("comp_www","Интернет","Компьютеры и Интернет");
insert into genres(genre,subsection,section) values("comp_programming","Программирование","Компьютеры и Интернет");
insert into genres(genre,subsection,section) values("comp_hard","Компьютерное железо","Компьютеры и Интернет");
insert into genres(genre,subsection,section) values("comp_soft","Программы","Компьютеры и Интернет");
insert into genres(genre,subsection,section) values("comp_db","Базы данных","Компьютеры и Интернет");
insert into genres(genre,subsection,section) values("comp_osnet","ОС и Сети","Компьютеры и Интернет");
insert into genres(genre,subsection,section) values("computers","Прочая околокомпьтерная литература","Компьютеры и Интернет");
insert into genres(genre,subsection,section) values("ref_encyc","Энциклопедии","Справочная литература");
insert into genres(genre,subsection,section) values("ref_dict","Словари","Справочная литература");
insert into genres(genre,subsection,section) values("ref_ref","Справочники","Справочная литература");
insert into genres(genre,subsection,section) values("ref_guide","Руководства","Справочная литература");
insert into genres(genre,subsection,section) values("reference","Прочая справочная литература","Справочная литература");
insert into genres(genre,subsection,section) values("nonf_biography","Биографии и Мемуары","Документальная литература");
insert into genres(genre,subsection,section) values("nonf_publicism","Публицистика","Документальная литература");
insert into genres(genre,subsection,section) values("nonf_criticism","Критика","Документальная литература");
insert into genres(genre,subsection,section) values("design","Искусство и Дизайн","Документальная литература");
insert into genres(genre,subsection,section) values("nonfiction","Прочая документальная литература","Документальная литература");
insert into genres(genre,subsection,section) values("religion_rel","Религия","Религия и духовность");
insert into genres(genre,subsection,section) values("religion_esoterics","Эзотерика","Религия и духовность");
insert into genres(genre,subsection,section) values("religion_self","Самосовершенствование","Религия и духовность");
insert into genres(genre,subsection,section) values("religion","Прочая религионая литература","Религия и духовность");
insert into genres(genre,subsection,section) values("humor_anecdote","Анекдоты","Юмор");
insert into genres(genre,subsection,section) values("humor_prose","Юмористическая проза","Юмор");
insert into genres(genre,subsection,section) values("humor_verse","Юмористические стихи","Юмор");
insert into genres(genre,subsection,section) values("humor","Прочий юмор","Юмор");
insert into genres(genre,subsection,section) values("home_cooking","Кулинария","Дом и семья");
insert into genres(genre,subsection,section) values("home_pets","Домашние животные","Дом и семья");
insert into genres(genre,subsection,section) values("home_crafts","Хобби и ремесла","Дом и семья");
insert into genres(genre,subsection,section) values("home_entertain","Развлечения","Дом и семья");
insert into genres(genre,subsection,section) values("home_health","Здоровье","Дом и семья");
insert into genres(genre,subsection,section) values("home_garden","Сад и огород","Дом и семья");
insert into genres(genre,subsection,section) values("home_diy","Сделай сам","Дом и семья");
insert into genres(genre,subsection,section) values("home_sport","Спорт","Дом и семья");
insert into genres(genre,subsection,section) values("home_sex","Эротика, Секс","Дом и семья");
insert into genres(genre,subsection,section) values("home","Прочее домоводство","Дом и семья");
commit;
