SET NAMES 'utf8';
SET CHARACTER SET utf8;

insert into genres(genre,subsection,section) values("economics_ref","Деловая литература","Деловая литература");
insert into genres(genre,subsection,section) values("popular_business","Карьера, кадры","Деловая литература");
insert into genres(genre,subsection,section) values("org_behavior","Маркетинг, PR","Деловая литература");
insert into genres(genre,subsection,section) values("banking","Финансы","Деловая литература");
insert into genres(genre,subsection,section) values("economics","Экономика","Деловая литература");
insert into genres(genre,subsection,section) values("det_action","Боевик","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("detective","Детективы","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_irony","Иронический детектив, дамский детективный роман","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_history","Исторический детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_classic","Классический детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_crime","Криминальный детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_hard","Крутой детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_political","Политический детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_police","Полицейский детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_maniac","Про маньяков","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_su","Советский детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("thriller","Триллер","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("det_espionage","Шпионский детектив","Детективы и Триллеры");
insert into genres(genre,subsection,section) values("nonf_biography","Биографии и Мемуары","Документальная литература");
insert into genres(genre,subsection,section) values("nonf_military","Военная документалистика и аналитика","Документальная литература");
insert into genres(genre,subsection,section) values("military_special","Военное дело","Документальная литература");
insert into genres(genre,subsection,section) values("travel_notes","География, путевые заметки","Документальная литература");
insert into genres(genre,subsection,section) values("nonfiction","Документальная литература","Документальная литература");
insert into genres(genre,subsection,section) values("nonf_publicism","Публицистика","Документальная литература");
insert into genres(genre,subsection,section) values("auto_regulations","Автомобили и ПДД","Дом и семья");
insert into genres(genre,subsection,section) values("home_sport","Боевые искусства, спорт","Дом и семья");
insert into genres(genre,subsection,section) values("home_pets","Домашние животные","Дом и семья");
insert into genres(genre,subsection,section) values("home","Домоводство","Дом и семья");
insert into genres(genre,subsection,section) values("home_health","Здоровье","Дом и семья");
insert into genres(genre,subsection,section) values("home_collecting","Коллекционирование","Дом и семья");
insert into genres(genre,subsection,section) values("home_cooking","Кулинария","Дом и семья");
insert into genres(genre,subsection,section) values("sci_pedagogy","Педагогика, воспитание детей, литература для родителей","Дом и семья");
insert into genres(genre,subsection,section) values("home_entertain","Развлечения","Дом и семья");
insert into genres(genre,subsection,section) values("home_garden","Сад и огород","Дом и семья");
insert into genres(genre,subsection,section) values("home_diy","Сделай сам","Дом и семья");
insert into genres(genre,subsection,section) values("family","Семейные отношения","Дом и семья");
insert into genres(genre,subsection,section) values("home_sex","Семейные отношения, секс","Дом и семья");
insert into genres(genre,subsection,section) values("home_crafts","Хобби и ремесла","Дом и семья");
insert into genres(genre,subsection,section) values("drama_antique","Античная драма","Драматургия");
insert into genres(genre,subsection,section) values("drama","Драма","Драматургия");
insert into genres(genre,subsection,section) values("dramaturgy","Драматургия","Драматургия");
insert into genres(genre,subsection,section) values("comedy","Комедия","Драматургия");
insert into genres(genre,subsection,section) values("vaudeville","Мистерия, буффонада, водевиль","Драматургия");
insert into genres(genre,subsection,section) values("screenplays","Сценарий","Драматургия");
insert into genres(genre,subsection,section) values("tragedy","Трагедия","Драматургия");
insert into genres(genre,subsection,section) values("painting","Живопись, альбомы, иллюстрированные каталоги","Искусство, Искусствоведение, Дизайн");
insert into genres(genre,subsection,section) values("design","Искусство и Дизайн","Искусство, Искусствоведение, Дизайн");
insert into genres(genre,subsection,section) values("art_criticism","Искусствоведение","Искусство, Искусствоведение, Дизайн");
insert into genres(genre,subsection,section) values("cine","Кино","Искусство, Искусствоведение, Дизайн");
insert into genres(genre,subsection,section) values("nonf_criticism","Критика","Искусство, Искусствоведение, Дизайн");
insert into genres(genre,subsection,section) values("sci_culture","Культурология","Искусство, Искусствоведение, Дизайн");
insert into genres(genre,subsection,section) values("art_world_culture","Мировая художественная культура","Искусство, Искусствоведение, Дизайн");
insert into genres(genre,subsection,section) values("music","Музыка","Искусство, Искусствоведение, Дизайн");
insert into genres(genre,subsection,section) values("notes","Партитуры","Искусство, Искусствоведение, Дизайн");
insert into genres(genre,subsection,section) values("architecture_book","Скульптура и архитектура","Искусство, Искусствоведение, Дизайн");
insert into genres(genre,subsection,section) values("theatre","Театр","Искусство, Искусствоведение, Дизайн");
insert into genres(genre,subsection,section) values("computers","Зарубежная компьютерная, околокомпьютерная литература","Компьютеры и Интернет");
insert into genres(genre,subsection,section) values("аппаратное обеспечение, цифровая обработка сигналов (comp_hard","Компьютерное 'железо'","Компьютеры и Интернет");
insert into genres(genre,subsection,section) values("comp_www","ОС и Сети, интернет","Компьютеры и Интернет");
insert into genres(genre,subsection,section) values("comp_db","Программирование, программы, базы данных","Компьютеры и Интернет");
insert into genres(genre,subsection,section) values("tbg_computers","Учебные пособия, самоучители","Компьютеры и Интернет");
insert into genres(genre,subsection,section) values("children","Детская литература","Литература для детей");
insert into genres(genre,subsection,section) values("child_education","Детская образовательная литература","Литература для детей");
insert into genres(genre,subsection,section) values("child_det","Детская остросюжетная литература","Литература для детей");
insert into genres(genre,subsection,section) values("foreign_children","Зарубежная литература для детей","Литература для детей");
insert into genres(genre,subsection,section) values("prose_game","Игры, упражнения для детей","Литература для детей");
insert into genres(genre,subsection,section) values("child_classical","Классическая детская литература","Литература для детей");
insert into genres(genre,subsection,section) values("child_prose","Проза для детей","Литература для детей");
insert into genres(genre,subsection,section) values("child_tale_rus","Русские сказки","Литература для детей");
insert into genres(genre,subsection,section) values("child_tale","Сказки народов мира","Литература для детей");
insert into genres(genre,subsection,section) values("child_verse","Стихи для детей","Литература для детей");
insert into genres(genre,subsection,section) values("child_sf","Фантастика для детей","Литература для детей");
insert into genres(genre,subsection,section) values("love_history","Исторические любовные романы","Любовные романы");
insert into genres(genre,subsection,section) values("love_short","Короткие любовные романы","Любовные романы");
insert into genres(genre,subsection,section) values("love_sf","Любовное фэнтези, любовно-фантастические романы","Любовные романы");
insert into genres(genre,subsection,section) values("love","Любовные романы","Любовные романы");
insert into genres(genre,subsection,section) values("love_detective","Остросюжетные любовные романы","Любовные романы");
insert into genres(genre,subsection,section) values("love_hard","Порно","Любовные романы");
insert into genres(genre,subsection,section) values("love_contemporary","Современные любовные романы","Любовные романы");
insert into genres(genre,subsection,section) values("love_erotica","Эротическая литература","Любовные романы");
insert into genres(genre,subsection,section) values("sci_medicine_alternative","Альтернативная медицина","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_theories","Альтернативные науки и научные теории","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_cosmos","Астрономия и Космос","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_biology","Биология, биофизика, биохимия","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_botany","Ботаника","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_veterinary","Ветеринария","Наука, Образование");
insert into genres(genre,subsection,section) values("military_history","Военная история","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_oriental","Востоковедение","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_geo","Геология и география","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_state","Государство и право","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_popular","Зарубежная образовательная литература, зарубежная прикладная, научно-популярная литература","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_zoo","Зоология","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_history","История","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_philology","Литературоведение","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_math","Математика","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_medicine","Медицина","Наука, Образование");
insert into genres(genre,subsection,section) values("science","Научная литература","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_social_studies","Обществознание, социология","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_politics","Политика","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_psychology","Психология и психотерапия","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_phys","Физика","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_philosophy","Философия","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_chem","Химия","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_ecology","Экология","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_economy","Экономика","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_juris","Юриспруденция","Наука, Образование");
insert into genres(genre,subsection,section) values("sci_linguistic","Языкознание, иностранные языки","Наука, Образование");
insert into genres(genre,subsection,section) values("palindromes","Визуальная и экспериментальная поэзия, верлибры, палиндромы","Поэзия");
insert into genres(genre,subsection,section) values("poetry_for_classical","Классическая зарубежная поэзия","Поэзия");
insert into genres(genre,subsection,section) values("poetry_classical","Классическая поэзия","Поэзия");
insert into genres(genre,subsection,section) values("poetry_rus_classical","Классическая русская поэзия","Поэзия");
insert into genres(genre,subsection,section) values("lyrics","Лирика","Поэзия");
insert into genres(genre,subsection,section) values("song_poetry","Песенная поэзия","Поэзия");
insert into genres(genre,subsection,section) values("poetry","Поэзия","Поэзия");
insert into genres(genre,subsection,section) values("poetry_east","Поэзия Востока","Поэзия");
insert into genres(genre,subsection,section) values("poem","Поэма, эпическая поэзия","Поэзия");
insert into genres(genre,subsection,section) values("poetry_for_modern","Современная зарубежная поэзия","Поэзия");
insert into genres(genre,subsection,section) values("poetry_modern","Современная поэзия","Поэзия");
insert into genres(genre,subsection,section) values("poetry_rus_modern","Современная русская поэзия","Поэзия");
insert into genres(genre,subsection,section) values("humor_verse","Юмористические стихи, басни","Поэзия");
insert into genres(genre,subsection,section) values("adv_story","Авантюрный роман","Приключения");
insert into genres(genre,subsection,section) values("adv_indian","Вестерн, про индейцев","Приключения");
insert into genres(genre,subsection,section) values("adv_history","Исторические приключения","Приключения");
insert into genres(genre,subsection,section) values("adv_maritime","Морские приключения","Приключения");
insert into genres(genre,subsection,section) values("adventure","Приключения","Приключения");
insert into genres(genre,subsection,section) values("adv_modern","Приключения в современном мире","Приключения");
insert into genres(genre,subsection,section) values("child_adv","Приключения для детей и подростков","Приключения");
insert into genres(genre,subsection,section) values("adv_animal","Природа и животные","Приключения");
insert into genres(genre,subsection,section) values("adv_geo","Путешествия и география","Приключения");
insert into genres(genre,subsection,section) values("tale_chivalry","Рыцарский роман","Приключения");
insert into genres(genre,subsection,section) values("aphorisms","Афоризмы, цитаты","Проза");
insert into genres(genre,subsection,section) values("gothic_novel","Готический роман","Проза");
insert into genres(genre,subsection,section) values("foreign_prose","Зарубежная классическая проза","Проза");
insert into genres(genre,subsection,section) values("prose_history","Историческая проза","Проза");
insert into genres(genre,subsection,section) values("prose_classic","Классическая проза","Проза");
insert into genres(genre,subsection,section) values("literature_18","Классическая проза XVII-XVIII веков","Проза");
insert into genres(genre,subsection,section) values("literature_19","Классическая проза ХIX века","Проза");
insert into genres(genre,subsection,section) values("literature_20","Классическая проза ХX века","Проза");
insert into genres(genre,subsection,section) values("prose_counter","Контркультура","Проза");
insert into genres(genre,subsection,section) values("prose_magic","Магический реализм","Проза");
insert into genres(genre,subsection,section) values("story","Малые литературные формы прозы: рассказы, эссе, новеллы, феерия","Проза");
insert into genres(genre,subsection,section) values("prose","Проза","Проза");
insert into genres(genre,subsection,section) values("prose_military","Проза о войне","Проза");
insert into genres(genre,subsection,section) values("great_story","Роман, повесть","Проза");
insert into genres(genre,subsection,section) values("prose_rus_classic","Русская классическая проза","Проза");
insert into genres(genre,subsection,section) values("prose_su_classics","Советская классическая проза","Проза");
insert into genres(genre,subsection,section) values("prose_contemporary","Современная русская и зарубежная проза","Проза");
insert into genres(genre,subsection,section) values("foreign_antique","Средневековая классическая проза","Проза");
insert into genres(genre,subsection,section) values("prose_abs","Фантасмагория, абсурдистская проза","Проза");
insert into genres(genre,subsection,section) values("prose_neformatny","Экспериментальная, неформатная проза","Проза");
insert into genres(genre,subsection,section) values("epistolary_fiction","Эпистолярная проза","Проза");
insert into genres(genre,subsection,section) values("periodic","Журналы, газеты","Прочее");
insert into genres(genre,subsection,section) values("comics","Комиксы","Прочее");
insert into genres(genre,subsection,section) values("unfinished","Незавершенное","Прочее");
insert into genres(genre,subsection,section) values("other","Неотсортированное","Прочее");
insert into genres(genre,subsection,section) values("network_literature","Самиздат, сетевая литература","Прочее");
insert into genres(genre,subsection,section) values("fanfiction","Фанфик","Прочее");
insert into genres(genre,subsection,section) values("astrology","Астрология и хиромантия","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("religion_budda","Буддизм","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("religion_hinduism","Индуизм","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("religion_islam","Ислам","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("religion_judaism","Иудаизм","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("religion_catholicism","Католицизм","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("religion_orthodoxy","Православие","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("religion_protestantism","Протестантизм","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("sci_religion","Религиоведение","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("religion","Религия, религиозная литература","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("religion_self","Самосовершенствование","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("religion_christianity","Христианство","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("religion_esoterics","Эзотерика, эзотерическая литература","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("religion_paganism","Язычество","Религия, духовность, эзотерика");
insert into genres(genre,subsection,section) values("geo_guides","Путеводители, карты, атласы","Справочная литература");
insert into genres(genre,subsection,section) values("ref_guide","Руководства","Справочная литература");
insert into genres(genre,subsection,section) values("ref_dict","Словари","Справочная литература");
insert into genres(genre,subsection,section) values("reference","Справочная литература","Справочная литература");
insert into genres(genre,subsection,section) values("ref_ref","Справочники","Справочная литература");
insert into genres(genre,subsection,section) values("ref_encyc","Энциклопедии","Справочная литература");
insert into genres(genre,subsection,section) values("antique","antique","Старинное");
insert into genres(genre,subsection,section) values("antique_ant","Античная литература","Старинное");
insert into genres(genre,subsection,section) values("antique_east","Древневосточная литература","Старинное");
insert into genres(genre,subsection,section) values("antique_russian","Древнерусская литература","Старинное");
insert into genres(genre,subsection,section) values("antique_european","Европейская старинная литература","Старинное");
insert into genres(genre,subsection,section) values("auto_business","Автодело","Техника");
insert into genres(genre,subsection,section) values("military_weapon","Военное дело, военная техника и вооружение","Техника");
insert into genres(genre,subsection,section) values("equ_history","История техники","Техника");
insert into genres(genre,subsection,section) values("sci_metal","Металлургия","Техника");
insert into genres(genre,subsection,section) values("sci_radio","Радиоэлектроника","Техника");
insert into genres(genre,subsection,section) values("sci_build","Строительство и сопромат","Техника");
insert into genres(genre,subsection,section) values("sci_tech","Технические науки","Техника");
insert into genres(genre,subsection,section) values("sci_transport","Транспорт и авиация","Техника");
insert into genres(genre,subsection,section) values("sci_textbook","Учебники и пособия","Учебники и пособия");
insert into genres(genre,subsection,section) values("tbg_higher","Учебники и пособия ВУЗов","Учебники и пособия");
insert into genres(genre,subsection,section) values("tbg_secondary","Учебники и пособия для среднего и специального образования","Учебники и пособия");
insert into genres(genre,subsection,section) values("tbg_school","Школьные учебники и пособия, рефераты, шпаргалки","Учебники и пособия");
insert into genres(genre,subsection,section) values("sf_history","Альтернативная история, попаданцы","Фантастика");
insert into genres(genre,subsection,section) values("sf_action","Боевая фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_heroic","Героическая фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_fantasy_city","Городское фэнтези","Фантастика");
insert into genres(genre,subsection,section) values("sf_detective","Детективная фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_cyberpunk","Киберпанк","Фантастика");
insert into genres(genre,subsection,section) values("sf_space","Космическая фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_mystic","Мистика","Фантастика");
insert into genres(genre,subsection,section) values("fairy_fantasy","Мифологическое фэнтези","Фантастика");
insert into genres(genre,subsection,section) values("sf","Научная Фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_postapocalyptic","Постапокалипсис","Фантастика");
insert into genres(genre,subsection,section) values("russian_fantasy","Славянское фэнтези","Фантастика");
insert into genres(genre,subsection,section) values("modern_tale","Современная сказка","Фантастика");
insert into genres(genre,subsection,section) values("sf_social","Социально-психологическая фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_stimpank","Стимпанк","Фантастика");
insert into genres(genre,subsection,section) values("sf_technofantasy","Технофэнтези","Фантастика");
insert into genres(genre,subsection,section) values("sf_horror","Ужасы","Фантастика");
insert into genres(genre,subsection,section) values("sf_etc","Фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_fantasy","Фэнтези","Фантастика");
insert into genres(genre,subsection,section) values("hronoopera","Хроноопера","Фантастика");
insert into genres(genre,subsection,section) values("sf_epic","Эпическая фантастика","Фантастика");
insert into genres(genre,subsection,section) values("sf_humor","Юмористическая фантастика","Фантастика");
insert into genres(genre,subsection,section) values("epic","Былины, эпопея","Фольклор");
insert into genres(genre,subsection,section) values("child_folklore","Детский фольклор","Фольклор");
insert into genres(genre,subsection,section) values("antique_myths","Мифы. Легенды. Эпос","Фольклор");
insert into genres(genre,subsection,section) values("folk_songs","Народные песни","Фольклор");
insert into genres(genre,subsection,section) values("folk_tale","Народные сказки","Фольклор");
insert into genres(genre,subsection,section) values("proverbs","Пословицы, поговорки","Фольклор");
insert into genres(genre,subsection,section) values("folklore","Фольклор, загадки folklore","Фольклор");
insert into genres(genre,subsection,section) values("limerick","Частушки, прибаутки, потешки","Фольклор");
insert into genres(genre,subsection,section) values("humor_anecdote","Анекдоты","Юмор");
insert into genres(genre,subsection,section) values("humor_satire","Сатира","Юмор");
insert into genres(genre,subsection,section) values("humor","Юмор","Юмор");
insert into genres(genre,subsection,section) values("humor_prose","Юмористическая проза","Юмор");
commit;
