SET NAMES 'utf8';
SET CHARACTER SET utf8;

update genres set section="Деловая литература", subsection="Деловая литература" where genre="economics_ref";
update genres set section="Деловая литература", subsection="Карьера, кадры" where genre="popular_business";
update genres set section="Деловая литература", subsection="Маркетинг, PR" where genre="org_behavior";
update genres set section="Деловая литература", subsection="Финансы" where genre="banking";
update genres set section="Деловая литература", subsection="Экономика" where genre="economics";
update genres set section="Детективы и Триллеры", subsection="Боевик" where genre="det_action";
update genres set section="Детективы и Триллеры", subsection="Детективы" where genre="detective";
update genres set section="Детективы и Триллеры", subsection="Иронический детектив, дамский детективный роман" where genre="det_irony";
update genres set section="Детективы и Триллеры", subsection="Исторический детектив" where genre="det_history";
update genres set section="Детективы и Триллеры", subsection="Классический детектив" where genre="det_classic";
update genres set section="Детективы и Триллеры", subsection="Криминальный детектив" where genre="det_crime";
update genres set section="Детективы и Триллеры", subsection="Крутой детектив" where genre="det_hard";
update genres set section="Детективы и Триллеры", subsection="Политический детектив" where genre="det_political";
update genres set section="Детективы и Триллеры", subsection="Полицейский детектив" where genre="det_police";
update genres set section="Детективы и Триллеры", subsection="Про маньяков" where genre="det_maniac";
update genres set section="Детективы и Триллеры", subsection="Советский детектив" where genre="det_su";
update genres set section="Детективы и Триллеры", subsection="Триллер" where genre="thriller";
update genres set section="Детективы и Триллеры", subsection="Шпионский детектив" where genre="det_espionage";
update genres set section="Документальная литература", subsection="Биографии и Мемуары" where genre="nonf_biography";
update genres set section="Документальная литература", subsection="Военная документалистика и аналитика" where genre="nonf_military";
update genres set section="Документальная литература", subsection="Военное дело" where genre="military_special";
update genres set section="Документальная литература", subsection="География, путевые заметки" where genre="travel_notes";
update genres set section="Документальная литература", subsection="Документальная литература" where genre="nonfiction";
update genres set section="Документальная литература", subsection="Публицистика" where genre="nonf_publicism";
update genres set section="Дом и семья", subsection="Автомобили и ПДД" where genre="auto_regulations";
update genres set section="Дом и семья", subsection="Боевые искусства, спорт" where genre="home_sport";
update genres set section="Дом и семья", subsection="Домашние животные" where genre="home_pets";
update genres set section="Дом и семья", subsection="Домоводство" where genre="home";
update genres set section="Дом и семья", subsection="Здоровье" where genre="home_health";
update genres set section="Дом и семья", subsection="Коллекционирование" where genre="home_collecting";
update genres set section="Дом и семья", subsection="Кулинария" where genre="home_cooking";
update genres set section="Дом и семья", subsection="Педагогика, воспитание детей, литература для родителей" where genre="sci_pedagogy";
update genres set section="Дом и семья", subsection="Развлечения" where genre="home_entertain";
update genres set section="Дом и семья", subsection="Сад и огород" where genre="home_garden";
update genres set section="Дом и семья", subsection="Сделай сам" where genre="home_diy";
update genres set section="Дом и семья", subsection="Семейные отношения" where genre="family";
update genres set section="Дом и семья", subsection="Семейные отношения, секс" where genre="home_sex";
update genres set section="Дом и семья", subsection="Хобби и ремесла" where genre="home_crafts";
update genres set section="Драматургия", subsection="Античная драма" where genre="drama_antique";
update genres set section="Драматургия", subsection="Драма" where genre="drama";
update genres set section="Драматургия", subsection="Драматургия" where genre="dramaturgy";
update genres set section="Драматургия", subsection="Комедия" where genre="comedy";
update genres set section="Драматургия", subsection="Мистерия, буффонада, водевиль" where genre="vaudeville";
update genres set section="Драматургия", subsection="Сценарий" where genre="screenplays";
update genres set section="Драматургия", subsection="Трагедия" where genre="tragedy";
update genres set section="Искусство, Искусствоведение, Дизайн", subsection="Живопись, альбомы, иллюстрированные каталоги" where genre="painting";
update genres set section="Искусство, Искусствоведение, Дизайн", subsection="Искусство и Дизайн" where genre="design";
update genres set section="Искусство, Искусствоведение, Дизайн", subsection="Искусствоведение" where genre="art_criticism";
update genres set section="Искусство, Искусствоведение, Дизайн", subsection="Кино" where genre="cine";
update genres set section="Искусство, Искусствоведение, Дизайн", subsection="Критика" where genre="nonf_criticism";
update genres set section="Искусство, Искусствоведение, Дизайн", subsection="Культурология" where genre="sci_culture";
update genres set section="Искусство, Искусствоведение, Дизайн", subsection="Мировая художественная культура" where genre="art_world_culture";
update genres set section="Искусство, Искусствоведение, Дизайн", subsection="Музыка" where genre="music";
update genres set section="Искусство, Искусствоведение, Дизайн", subsection="Партитуры" where genre="notes";
update genres set section="Искусство, Искусствоведение, Дизайн", subsection="Скульптура и архитектура" where genre="architecture_book";
update genres set section="Искусство, Искусствоведение, Дизайн", subsection="Театр" where genre="theatre";
update genres set section="Компьютеры и Интернет", subsection="Зарубежная компьютерная, околокомпьютерная литература" where genre="computers";
update genres set section="Компьютеры и Интернет", subsection="Компьютерное 'железо'" where genre="comp_hard";
update genres set section="Компьютеры и Интернет", subsection="ОС и Сети, интернет" where genre="comp_www";
update genres set section="Компьютеры и Интернет", subsection="Программирование, программы, базы данных" where genre="comp_db";
update genres set section="Компьютеры и Интернет", subsection="Учебные пособия, самоучители" where genre="tbg_computers";
update genres set section="Литература для детей", subsection="Детская литература" where genre="children";
update genres set section="Литература для детей", subsection="Детская образовательная литература" where genre="child_education";
update genres set section="Литература для детей", subsection="Детская остросюжетная литература" where genre="child_det";
update genres set section="Литература для детей", subsection="Зарубежная литература для детей" where genre="foreign_children";
update genres set section="Литература для детей", subsection="Игры, упражнения для детей" where genre="prose_game";
update genres set section="Литература для детей", subsection="Классическая детская литература" where genre="child_classical";
update genres set section="Литература для детей", subsection="Проза для детей" where genre="child_prose";
update genres set section="Литература для детей", subsection="Русские сказки" where genre="child_tale_rus";
update genres set section="Литература для детей", subsection="Сказки народов мира" where genre="child_tale";
update genres set section="Литература для детей", subsection="Стихи для детей" where genre="child_verse";
update genres set section="Литература для детей", subsection="Фантастика для детей" where genre="child_sf";
update genres set section="Любовные романы", subsection="Исторические любовные романы" where genre="love_history";
update genres set section="Любовные романы", subsection="Короткие любовные романы" where genre="love_short";
update genres set section="Любовные романы", subsection="Любовное фэнтези, любовно-фантастические романы" where genre="love_sf";
update genres set section="Любовные романы", subsection="Любовные романы" where genre="love";
update genres set section="Любовные романы", subsection="Остросюжетные любовные романы" where genre="love_detective";
update genres set section="Любовные романы", subsection="Порно" where genre="love_hard";
update genres set section="Любовные романы", subsection="Современные любовные романы" where genre="love_contemporary";
update genres set section="Любовные романы", subsection="Эротическая литература" where genre="love_erotica";
update genres set section="Наука, Образование", subsection="Альтернативная медицина" where genre="sci_medicine_alternative";
update genres set section="Наука, Образование", subsection="Альтернативные науки и научные теории" where genre="sci_theories";
update genres set section="Наука, Образование", subsection="Астрономия и Космос" where genre="sci_cosmos";
update genres set section="Наука, Образование", subsection="Биология, биофизика, биохимия" where genre="sci_biology";
update genres set section="Наука, Образование", subsection="Ботаника" where genre="sci_botany";
update genres set section="Наука, Образование", subsection="Ветеринария" where genre="sci_veterinary";
update genres set section="Наука, Образование", subsection="Военная история" where genre="military_history";
update genres set section="Наука, Образование", subsection="Востоковедение" where genre="sci_oriental";
update genres set section="Наука, Образование", subsection="Геология и география" where genre="sci_geo";
update genres set section="Наука, Образование", subsection="Государство и право" where genre="sci_state";
update genres set section="Наука, Образование", subsection="Зарубежная образовательная литература, зарубежная прикладная, научно-популярная литература" where genre="sci_popular";
update genres set section="Наука, Образование", subsection="Зоология" where genre="sci_zoo";
update genres set section="Наука, Образование", subsection="История" where genre="sci_history";
update genres set section="Наука, Образование", subsection="Литературоведение" where genre="sci_philology";
update genres set section="Наука, Образование", subsection="Математика" where genre="sci_math";
update genres set section="Наука, Образование", subsection="Медицина" where genre="sci_medicine";
update genres set section="Наука, Образование", subsection="Научная литература" where genre="science";
update genres set section="Наука, Образование", subsection="Обществознание, социология" where genre="sci_social_studies";
update genres set section="Наука, Образование", subsection="Политика" where genre="sci_politics";
update genres set section="Наука, Образование", subsection="Психология и психотерапия" where genre="sci_psychology";
update genres set section="Наука, Образование", subsection="Физика" where genre="sci_phys";
update genres set section="Наука, Образование", subsection="Философия" where genre="sci_philosophy";
update genres set section="Наука, Образование", subsection="Химия" where genre="sci_chem";
update genres set section="Наука, Образование", subsection="Экология" where genre="sci_ecology";
update genres set section="Наука, Образование", subsection="Экономика" where genre="sci_economy";
update genres set section="Наука, Образование", subsection="Юриспруденция" where genre="sci_juris";
update genres set section="Наука, Образование", subsection="Языкознание, иностранные языки" where genre="sci_linguistic";
update genres set section="Поэзия", subsection="Визуальная и экспериментальная поэзия, верлибры, палиндромы" where genre="palindromes";
update genres set section="Поэзия", subsection="Классическая зарубежная поэзия" where genre="poetry_for_classical";
update genres set section="Поэзия", subsection="Классическая поэзия" where genre="poetry_classical";
update genres set section="Поэзия", subsection="Классическая русская поэзия" where genre="poetry_rus_classical";
update genres set section="Поэзия", subsection="Лирика" where genre="lyrics";
update genres set section="Поэзия", subsection="Песенная поэзия" where genre="song_poetry";
update genres set section="Поэзия", subsection="Поэзия" where genre="poetry";
update genres set section="Поэзия", subsection="Поэзия Востока" where genre="poetry_east";
update genres set section="Поэзия", subsection="Поэма, эпическая поэзия" where genre="poem";
update genres set section="Поэзия", subsection="Современная зарубежная поэзия" where genre="poetry_for_modern";
update genres set section="Поэзия", subsection="Современная поэзия" where genre="poetry_modern";
update genres set section="Поэзия", subsection="Современная русская поэзия" where genre="poetry_rus_modern";
update genres set section="Поэзия", subsection="Юмористические стихи, басни" where genre="humor_verse";
update genres set section="Приключения", subsection="Авантюрный роман" where genre="adv_story";
update genres set section="Приключения", subsection="Вестерн, про индейцев" where genre="adv_indian";
update genres set section="Приключения", subsection="Исторические приключения" where genre="adv_history";
update genres set section="Приключения", subsection="Морские приключения" where genre="adv_maritime";
update genres set section="Приключения", subsection="Приключения" where genre="adventure";
update genres set section="Приключения", subsection="Приключения в современном мире" where genre="adv_modern";
update genres set section="Приключения", subsection="Приключения для детей и подростков" where genre="child_adv";
update genres set section="Приключения", subsection="Природа и животные" where genre="adv_animal";
update genres set section="Приключения", subsection="Путешествия и география" where genre="adv_geo";
update genres set section="Приключения", subsection="Рыцарский роман" where genre="tale_chivalry";
update genres set section="Проза", subsection="Афоризмы, цитаты" where genre="aphorisms";
update genres set section="Проза", subsection="Готический роман" where genre="gothic_novel";
update genres set section="Проза", subsection="Зарубежная классическая проза" where genre="foreign_prose";
update genres set section="Проза", subsection="Историческая проза" where genre="prose_history";
update genres set section="Проза", subsection="Классическая проза" where genre="prose_classic";
update genres set section="Проза", subsection="Классическая проза XVII-XVIII веков" where genre="literature_18";
update genres set section="Проза", subsection="Классическая проза ХIX века" where genre="literature_19";
update genres set section="Проза", subsection="Классическая проза ХX века" where genre="literature_20";
update genres set section="Проза", subsection="Контркультура" where genre="prose_counter";
update genres set section="Проза", subsection="Магический реализм" where genre="prose_magic";
update genres set section="Проза", subsection="Малые литературные формы прозы: рассказы, эссе, новеллы, феерия" where genre="story";
update genres set section="Проза", subsection="Проза" where genre="prose";
update genres set section="Проза", subsection="Проза о войне" where genre="prose_military";
update genres set section="Проза", subsection="Роман, повесть" where genre="great_story";
update genres set section="Проза", subsection="Русская классическая проза" where genre="prose_rus_classic";
update genres set section="Проза", subsection="Советская классическая проза" where genre="prose_su_classics";
update genres set section="Проза", subsection="Современная русская и зарубежная проза" where genre="prose_contemporary";
update genres set section="Проза", subsection="Средневековая классическая проза" where genre="foreign_antique";
update genres set section="Проза", subsection="Фантасмагория, абсурдистская проза" where genre="prose_abs";
update genres set section="Проза", subsection="Экспериментальная, неформатная проза" where genre="prose_neformatny";
update genres set section="Проза", subsection="Эпистолярная проза" where genre="epistolary_fiction";
update genres set section="Прочее", subsection="Журналы, газеты" where genre="periodic";
update genres set section="Прочее", subsection="Комиксы" where genre="comics";
update genres set section="Прочее", subsection="Незавершенное" where genre="unfinished";
update genres set section="Прочее", subsection="Неотсортированное" where genre="other";
update genres set section="Прочее", subsection="Самиздат, сетевая литература" where genre="network_literature";
update genres set section="Прочее", subsection="Фанфик" where genre="fanfiction";
update genres set section="Религия, духовность, эзотерика", subsection="Астрология и хиромантия" where genre="astrology";
update genres set section="Религия, духовность, эзотерика", subsection="Буддизм" where genre="religion_budda";
update genres set section="Религия, духовность, эзотерика", subsection="Индуизм" where genre="religion_hinduism";
update genres set section="Религия, духовность, эзотерика", subsection="Ислам" where genre="religion_islam";
update genres set section="Религия, духовность, эзотерика", subsection="Иудаизм" where genre="religion_judaism";
update genres set section="Религия, духовность, эзотерика", subsection="Католицизм" where genre="religion_catholicism";
update genres set section="Религия, духовность, эзотерика", subsection="Православие" where genre="religion_orthodoxy";
update genres set section="Религия, духовность, эзотерика", subsection="Протестантизм" where genre="religion_protestantism";
update genres set section="Религия, духовность, эзотерика", subsection="Религиоведение" where genre="sci_religion";
update genres set section="Религия, духовность, эзотерика", subsection="Религия, религиозная литература" where genre="religion";
update genres set section="Религия, духовность, эзотерика", subsection="Самосовершенствование" where genre="religion_self";
update genres set section="Религия, духовность, эзотерика", subsection="Христианство" where genre="religion_christianity";
update genres set section="Религия, духовность, эзотерика", subsection="Эзотерика, эзотерическая литература" where genre="religion_esoterics";
update genres set section="Религия, духовность, эзотерика", subsection="Язычество" where genre="religion_paganism";
update genres set section="Справочная литература", subsection="Путеводители, карты, атласы" where genre="geo_guides";
update genres set section="Справочная литература", subsection="Руководства" where genre="ref_guide";
update genres set section="Справочная литература", subsection="Словари" where genre="ref_dict";
update genres set section="Справочная литература", subsection="Справочная литература" where genre="reference";
update genres set section="Справочная литература", subsection="Справочники" where genre="ref_ref";
update genres set section="Справочная литература", subsection="Энциклопедии" where genre="ref_encyc";
update genres set section="Старинное", subsection="antique" where genre="antique";
update genres set section="Старинное", subsection="Античная литература" where genre="antique_ant";
update genres set section="Старинное", subsection="Древневосточная литература" where genre="antique_east";
update genres set section="Старинное", subsection="Древнерусская литература" where genre="antique_russian";
update genres set section="Старинное", subsection="Европейская старинная литература" where genre="antique_european";
update genres set section="Техника", subsection="Автодело" where genre="auto_business";
update genres set section="Техника", subsection="Военное дело, военная техника и вооружение" where genre="military_weapon";
update genres set section="Техника", subsection="История техники" where genre="equ_history";
update genres set section="Техника", subsection="Металлургия" where genre="sci_metal";
update genres set section="Техника", subsection="Радиоэлектроника" where genre="sci_radio";
update genres set section="Техника", subsection="Строительство и сопромат" where genre="sci_build";
update genres set section="Техника", subsection="Технические науки" where genre="sci_tech";
update genres set section="Техника", subsection="Транспорт и авиация" where genre="sci_transport";
update genres set section="Учебники и пособия", subsection="Учебники и пособия" where genre="sci_textbook";
update genres set section="Учебники и пособия", subsection="Учебники и пособия ВУЗов" where genre="tbg_higher";
update genres set section="Учебники и пособия", subsection="Учебники и пособия для среднего и специального образования" where genre="tbg_secondary";
update genres set section="Учебники и пособия", subsection="Школьные учебники и пособия, рефераты, шпаргалки" where genre="tbg_school";
update genres set section="Фантастика", subsection="Альтернативная история, попаданцы" where genre="sf_history";
update genres set section="Фантастика", subsection="Боевая фантастика" where genre="sf_action";
update genres set section="Фантастика", subsection="Героическая фантастика" where genre="sf_heroic";
update genres set section="Фантастика", subsection="Городское фэнтези" where genre="sf_fantasy_city";
update genres set section="Фантастика", subsection="Детективная фантастика" where genre="sf_detective";
update genres set section="Фантастика", subsection="Киберпанк" where genre="sf_cyberpunk";
update genres set section="Фантастика", subsection="Космическая фантастика" where genre="sf_space";
update genres set section="Фантастика", subsection="Мистика" where genre="sf_mystic";
update genres set section="Фантастика", subsection="Мифологическое фэнтези" where genre="fairy_fantasy";
update genres set section="Фантастика", subsection="Научная Фантастика" where genre="sf";
update genres set section="Фантастика", subsection="Постапокалипсис" where genre="sf_postapocalyptic";
update genres set section="Фантастика", subsection="Славянское фэнтези" where genre="russian_fantasy";
update genres set section="Фантастика", subsection="Современная сказка" where genre="modern_tale";
update genres set section="Фантастика", subsection="Социально-психологическая фантастика" where genre="sf_social";
update genres set section="Фантастика", subsection="Стимпанк" where genre="sf_stimpank";
update genres set section="Фантастика", subsection="Технофэнтези" where genre="sf_technofantasy";
update genres set section="Фантастика", subsection="Ужасы" where genre="sf_horror";
update genres set section="Фантастика", subsection="Фантастика" where genre="sf_etc";
update genres set section="Фантастика", subsection="Фэнтези" where genre="sf_fantasy";
update genres set section="Фантастика", subsection="Хроноопера" where genre="hronoopera";
update genres set section="Фантастика", subsection="Эпическая фантастика" where genre="sf_epic";
update genres set section="Фантастика", subsection="Юмористическая фантастика" where genre="sf_humor";
update genres set section="Фольклор", subsection="Былины, эпопея" where genre="epic";
update genres set section="Фольклор", subsection="Детский фольклор" where genre="child_folklore";
update genres set section="Фольклор", subsection="Мифы. Легенды. Эпос" where genre="antique_myths";
update genres set section="Фольклор", subsection="Народные песни" where genre="folk_songs";
update genres set section="Фольклор", subsection="Народные сказки" where genre="folk_tale";
update genres set section="Фольклор", subsection="Пословицы, поговорки" where genre="proverbs";
update genres set section="Фольклор", subsection="Фольклор, загадки folklore" where genre="folklore";
update genres set section="Фольклор", subsection="Частушки, прибаутки, потешки" where genre="limerick";
update genres set section="Юмор", subsection="Анекдоты" where genre="humor_anecdote";
update genres set section="Юмор", subsection="Сатира" where genre="humor_satire";
update genres set section="Юмор", subsection="Юмор" where genre="humor";
update genres set section="Юмор", subsection="Юмористическая проза" where genre="humor_prose";
commit;
