# Generated by Django 4.1.1 on 2022-09-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190129_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
