# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=1024)),
                ('filesize', models.IntegerField(default=0)),
                ('format', models.CharField(max_length=8)),
                ('cat_type', models.IntegerField(default=0)),
                ('registerdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('docdate', models.CharField(max_length=20)),
                ('favorite', models.IntegerField(default=0)),
                ('lang', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=256)),
                ('annotation', models.CharField(max_length=10000)),
                ('cover', models.CharField(max_length=32)),
                ('cover_type', models.CharField(max_length=32)),
                ('doublicat', models.IntegerField(default=0)),
                ('avail', models.IntegerField(default=0)),
                ('author', models.ManyToManyField(to='opds_catalog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='bookshelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opds_catalog.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_no', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opds_catalog.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=1024)),
                ('cat_type', models.IntegerField(default=0)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opds_catalog.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=32)),
                ('section', models.CharField(max_length=64)),
                ('subsection', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='bseries',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opds_catalog.Series'),
        ),
        migrations.AddField(
            model_name='book',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opds_catalog.Catalog'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='opds_catalog.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ManyToManyField(through='opds_catalog.bseries', to='opds_catalog.Series'),
        ),
    ]
