# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='counter',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='docdate',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='cat_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='series',
            name='ser',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
