# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='cat_size',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
