# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='cat_id',
            new_name='catalog',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
