# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 14:24
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0002_counters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counters',
            new_name='Counter',
        ),
        migrations.AlterModelManagers(
            name='counter',
            managers=[
                ('work', django.db.models.manager.Manager()),
            ],
        ),
    ]
