# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0003_auto_20161116_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='ser',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
