# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0003_catalog_cat_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='sAuthor',
            field=models.CharField(db_index=True, default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='book',
            name='sTitle',
            field=models.CharField(db_index=True, default=None, max_length=256),
        ),
    ]
