# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0003_auto_20160320_1724'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='counter',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='counter',
            name='id',
        ),
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
