# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0003_auto_20160303_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog_Book_Serialiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='filename',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='path',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='book',
            name='registerdate',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='series',
            name='ser',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterIndexTogether(
            name='author',
            index_together=set([('last_name', 'first_name')]),
        ),
        migrations.AlterIndexTogether(
            name='book',
            index_together=set([('title', 'format', 'filesize'), ('avail', 'doublicat')]),
        ),
        migrations.AlterIndexTogether(
            name='bseries',
            index_together=set([('book', 'ser')]),
        ),
        migrations.AlterIndexTogether(
            name='catalog',
            index_together=set([('cat_name', 'path')]),
        ),
    ]
