# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0004_auto_20160317_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='bauthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opds_catalog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='bgenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(through='opds_catalog.bauthor', to='opds_catalog.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(through='opds_catalog.bgenre', to='opds_catalog.Genre'),
        ),
        migrations.AddField(
            model_name='bgenre',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opds_catalog.Book'),
        ),
        migrations.AddField(
            model_name='bgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opds_catalog.Genre'),
        ),
        migrations.AddField(
            model_name='bauthor',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opds_catalog.Book'),
        ),
        migrations.AlterIndexTogether(
            name='bgenre',
            index_together=set([('book', 'genre')]),
        ),
        migrations.AlterIndexTogether(
            name='bauthor',
            index_together=set([('book', 'author')]),
        ),
    ]
