# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0004_auto_20161116_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='filename',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='book',
            name='path',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
