# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0004_auto_20160320_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='lang_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='lang_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='lang_code',
            field=models.IntegerField(default=0),
        ),
    ]
