# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0004_auto_20161114_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='sAuthor',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sTitle',
        ),
    ]
