# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0005_auto_20161114_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(db_index=True, default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='author',
            name='search_full_name',
            field=models.CharField(db_index=True, default=None, max_length=128),
        ),
        migrations.AlterIndexTogether(
            name='author',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
