# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0005_auto_20160718_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='lang_code',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='lang_code',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='series',
            name='lang_code',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
