# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0005_auto_20161204_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='position',
            field=models.FloatField(default=None, null=True),
        ),
    ]
