# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0006_auto_20161114_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='search_title',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='series',
            name='search_ser',
            field=models.CharField(db_index=True, default=None, max_length=80),
        ),
    ]
